name: Deploy Frontend to Railway

on:
  push:
    branches: [main]
    paths:
      - 'src/**'
      - 'public/**'
      - 'index.html'
      - 'package.json'
      - 'package-lock.json'
      - 'vite.config.ts'
      - 'tsconfig*.json'
      - 'tailwind.config.js'
      - 'postcss.config.js'
      - 'railway.json'

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    container: ghcr.io/railwayapp/cli:latest
    env:
      SVC_ID: ced5a086-32ca-4d0c-9830-b0892243c4ee
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Deploy Frontend to Railway
        run: railway up --service=${{ env.SVC_ID }}