name: Deploy Backend to Railway

on:
  push:
    branches: [main]
    paths:
      - 'server/**'

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    container: ghcr.io/railwayapp/cli:latest
    env:
      SVC_ID: 0a49cfcf-d7a0-43fb-b0ce-691a24074d64
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Deploy Backend to Railway
        working-directory: ./server
        run: railway up --service=${{ env.SVC_ID }} --detach